apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: url-shortner
  labels:
    app: analytics
spec:
  replicas: {{ .Values.analytics.replicas }}
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: asia-south1-docker.pkg.dev/acoustic-cirrus-439618-h8/analytics-service/analytics-service:{{ .Values.analytics.image.tag }}
          envFrom:
            - secretRef:
                name: analytics-env-secret
          ports:
            - containerPort: 3001
