apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: url-shortner
spec:
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
