apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: url-shortner
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: asia-south1-docker.pkg.dev/acoustic-cirrus-439618-h8/frontend-service/frontend-service:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "https://kagenou.xyz/api/shorten"
          ports:
            - containerPort: 3000
