apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortner-ingress
  namespace: url-shortner
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  tls:
    - hosts:
        - kagenou.xyz
      secretName: tls-secret
  rules:
    - host: "kagenou.xyz"
      http:
        paths:
          - pathType: Prefix
            path: "/api/shorten"
            backend:
              service:
                name: shortner-service
                port:
                  number: 3002
          - pathType: Prefix
            path: "/r/"
            backend:
              service:
                name: shortner-service
                port:
                  number: 3002
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
