appVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml : |
    global: 
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_config:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
            