apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shortner-service-monitor
  namespace: monitoring
  labels:
    release: prometheus

spec:
  selector:
    matchLabels: 
      app: shortner
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - url-shortner