apiVersion: v1
kind: Service
metadata:
  name: shortner-service
  namespace: url-shortner
spec:
  selector:
    app: shortner
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      name: http
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: metrics
  type: ClusterIP