frontend:
  replicas: 2
  image:
    tag: 5cd49b030f1cda09cf9a1ba0182686dd7aab69d8
shortner:
  replicas: 2
  image:
    tag: 5cd49b030f1cda09cf9a1ba0182686dd7aab69d8
analytics:
  replicas: 2
  image:
    tag: 5cd49b030f1cda09cf9a1ba0182686dd7aab69d8
ingress:
  host: kagenou.xyz
